name: merge rule
on: push
jobs:
  merge_rule:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20' 
        - name: Run merge-utils
          run: node ./utils/merge
        - uses: andstor/file-existence-action@v3
          id: check_rules
          with:
            files: desktop.json, mobile.json, desktop.thin.json, mobile.thin.json
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "chore(rules): auto export rules"
            # commit_user_name: "github-actions[bot]"
            # commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
            # commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
            file_pattern: "*.json"
